
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

interface EvidenceData {
    caseId: string;
    timestamp: string;
    analysisResult: any;
    userName: string;
}

export const generateEvidencePack = async (data: EvidenceData | null) => {
    const zip = new JSZip();
    const folder = zip.folder("DEFENSE_AI_EVIDENCE_PACK");

    if (!folder) return;

    // 1. Audit Log
    const auditLog = `
    ================================================
            DIGITAL FORENSIC AUDIT LOG
    ================================================
    Case ID: ${data?.caseId || 'UNKNOWN'}
    Timestamp: ${data?.timestamp || new Date().toISOString()}
    User: ${data?.userName || 'Anonymous'}
    ------------------------------------------------
    VERDICT: ${data?.analysisResult?.isDeepfake ? 'FAKE DETECTED' : 'AUTHENTIC MEDIA'}
    CONFIDENCE: ${data?.analysisResult?.confidence}%
    ------------------------------------------------
    
    HASH INTEGRITY CHECK:
    - Original File MD5: ${Math.random().toString(36).substring(2, 15)} (Simulated)
    - Analysis SHA-256: ${Math.random().toString(36).substring(2, 15)} (Simulated)

    Generated by DeepfakeDefense Platform
    `;

    folder.file("audit_log.txt", auditLog);

    // 2. JSON Analysis Data
    folder.file("analysis_metrics.json", JSON.stringify(data?.analysisResult || {}, null, 2));

    // 3. Technical Explanation HTML
    const htmlContent = `
    <html>
        <body style="font-family: monospace; padding: 20px; background: #f0f0f0;">
            <h1 style="color: #333;">Technical Findings</h1>
            <ul>
                <li><strong>Spatial Score:</strong> ${data?.analysisResult?.spatialScore}%</li>
                <li><strong>Temporal Score:</strong> ${data?.analysisResult?.temporalScore}%</li>
                <li><strong>Biological Consistency:</strong> ${data?.analysisResult?.biologicalScore}%</li>
            </ul>
        </body>
    </html>
    `;
    folder.file("technical_findings.html", htmlContent);

    // Generate and download
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, `Evidence_Pack_${data?.caseId || 'REPORT'}.zip`);
};
